name: Run Athenry Script

on:
    schedule:
        # triggering at 7:55am to avoid API overload
        - cron: '55 7 * * *'
    workflow_dispatch:

permissions:
    contents: write

jobs:
    run-athenry-script:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Run weather.sh
              run: ./weather.sh

            - name: Commit and push changes
              run: |
                git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git add .
                git commit -m "Automated: weather.sh" || echo "No changes to commit"
                git push origin main